### ISSUE TITLE
nginx reverse proxy is not working

### ISSUE THREAD

**Issue by mzramna** [coderaiser/cloudcmd#246]
i'm using the cloudcommander official docker,and it does not support the nginx reverse proxy,probly becouse of the javascript.
it says: "ENOENT: no such file or directory, lstat '/usr/src/app/cloudcommand'"

* **Version** (`cloudcmd -v`): v7.3.2
* **Node Version** : v8.1.3
* **OS** (`uname -a` on Linux): Linux 831994f55d41 4.19.38-sunxi #5.85 SMP Wed May 8 14:20:48 CEST 2019 armv7l GNU/Linux
* **Browser name/version**: google chrome 
* **Used Command Line Parameters**: docker default

**Comment by coderaiser** [comment]
Could you please show me your nginx config?

**Comment by mzramna** [comment]
this is the part relevant to cloud Commander: 

server {

        listen 80;
        listen 443;
location /cloudcommand {
                proxy_pass http://localhost:8000;
                subs_filter_types text/css text/xml;
                sub_filter 'action="'  'action="cloudcommand/';
                sub_filter 'href="'  'href="cloudcommand/';
                sub_filter 'src="'  'src="cloudcommand/';
                sub_filter_once off;
        }
}

**Comment by coderaiser** [comment]
Looks like you didn't set `prefix`, if you want access `Cloud Commander` on `/cloudcommand` url, you should run it with:

```sh
cloudcmd --prefix /cloudcommand
```

or save this option ones with:

```
cloudcmd --prefix /cloudcommand --save
```

And then just run `cloudcmd` with no options.

Is it helps?

**Comment by mzramna** [comment]
it worked thanks ^^

**Comment by brunoamaral** [comment]
How would this be configured in docker? I tried editing .cloudcmd.json but the setting doesn't seem to take effect.

**Comment by coderaiser** [comment]
@brunoamaral could you please provide more details, how do you run `docker container`?

**Comment by brunoamaral** [comment]
Sure thing. I am using docker-compose with the following:

```yaml
version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - /home/user/cloudcommander:/root
      - /mnt/hdd:/mnt/fs
    image: coderaiser/cloudcmd
    container_name: cloudcommander
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - "traefik.http.routers.cloudcommander.tls=true"
      # - "traefik.http.routers.cloudcommander.midddlewares=stsheaders"
      - "traefik.http.services.cloudcommander.loadbalancer.server.port=8000"
      - "traefik.http.routers.cloudcommander.rule=Host(`${DOMAIN_NAME_2}`) && PathPrefix(`/cloudcommand`)"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

**Comment by brunoamaral** [comment]
@coderaiser I am just trying to pass the Prefix setting to cloudcmd. Tried to edit the json file, but it seems to ignore it, or maybe I'm editing the wrong one.

**Comment by coderaiser** [comment]
@brunoamaral what `json` file have you edited? You can set [env variables](http://cloudcmd.io/#environment-variables-1) using `environment`:

```yml
version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - /home/user/cloudcommander:/root
      - /mnt/hdd:/mnt/fs
    image: coderaiser/cloudcmd
    environment:
      - CLOUDCMD_PREFIX='/hello'
    container_name: cloudcommander
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - "traefik.http.routers.cloudcommander.tls=true"
      # - "traefik.http.routers.cloudcommander.midddlewares=stsheaders"
      - "traefik.http.services.cloudcommander.loadbalancer.server.port=8000"
      - "traefik.http.routers.cloudcommander.rule=Host(`${DOMAIN_NAME_2}`) && PathPrefix(`/cloudcommand`)"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

But `CLOUDCMD_PREFIX` is not support right now, but that's a good idea for a pull request :).
It can be made editing [bin/cloudcmd.js](https://github.com/coderaiser/cloudcmd/blob/v14.1.2/bin/cloudcmd.js#L94-L95) in a similar way as with `root`.

[HELP.md](https://github.com/coderaiser/cloudcmd/blob/v14.1.2/HELP.md#environment-variables-1)  should also be edited.
