### ISSUE TITLE
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by praded2007** [coderaiser/cloudcmd#281]
Hello @coderaiser, great job.
I created a folder for myself along the way
for docker-compose:  /home/pi/smarthome/docker-compose.yml
 ```
web:
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/home/pi/smarthome/cloudcommander
    image: coderaiser/cloudcmd
```
for folder cloudcommander: /home/pi/smarthome/cloudcommander
When I try to install it, using the docker compose, an error pops up.
How do I install correctly?

* **v14.3.4** (`cloudcmd -v`): 
* **v12.16.1** `node -v`: 
* ** Raspbian Buster on Raspberry 4** (`uname -a` on Linux):
