### ISSUE TITLE
Add PUID & PGID settings docker

### ISSUE THREAD

**Issue by Toomblr** [coderaiser/cloudcmd#302]
It would be nice to run container as user. Because all new files/folders are now created as root. Aside from the security concerns this brings along.

**Comment by robflate** [comment]
I add `user: 1000:1000` (or whatever your UID and GID are) to my docker compose.

**Comment by Toomblr** [comment]
@robflate 
Like this:
`  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    environment:
      - user= 1000:1000
      - CLOUDCMD_AUTH=false
      - CLOUDCMD_USERNAME=$CLOUDCMD_USERNAME
      - CLOUDCMD_PASSWORD=$CLOUDCMD_PASSWORD`

Cause that doesn't work for me. Could be my own fault.

**Comment by robflate** [comment]
This is a cutdown version of my compose;

```
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    networks:
      - blah
    volumes:
      - /blah/code-server/.config:/home/coder/.config
      - /blah/code-server/.ssh:/home/coder/.ssh
      - /blah/code-server/.local:/home/coder/.local/share/code-server
    environment:
      PASSWORD: blah
      DOCKER_USER: blah
      LOG_LEVEL: info
      TRUST_PROXY: "true"
    user: 1000:1000
```

I create and CHOWN (1000:1000) the folders `code-server/.config`, `code-server/.ssh` and `code-server/.local` before running for the first time.

**Comment by Toomblr** [comment]
@robflate 

I did it like this, according to your compose example:

```
  cloudcmd:
    image: coderaiser/cloudcmd
    container_name: cloudcmd
    environment:
      - DOCKER_USER= michiel
      - CLOUDCMD_AUTH=false
      - CLOUDCMD_USERNAME=$CLOUDCMD_USERNAME
      - CLOUDCMD_PASSWORD=$CLOUDCMD_PASSWORD
      - user:1000:1000  
    security_opt:
      - no-new-privileges:true
    volumes:
      - ~:/root
      - /vol0:/vol0
      - /:/mnt/fs
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.26
```

Sadly, this doesn't make a difference
