### ISSUE TITLE
password hashing not the same - cant login

### ISSUE THREAD

**Issue by Daxcor69** [coderaiser/cloudcmd#346]
* **Version** (`cloudcmd -v`): v15.9.4
* **Node Version** `v15.9.4: 14.17.0
* **OS** (`uname -a` on Linux): Linux clientvm 5.4.0-72-generic #80-Ubuntu SMP

when I run at the cli :
```
 cloudcmd --username testserver --password testsever --auth --save --no-server
```
I get: 
```
{
    "name": "",
    "auth": true,
    "username": "testserver",
    "password": "315eb50893057c7159a6b7c728f73537cac0e5dbe9bc95e874c787cef9014b60d4ea27173a2dc4a392b5db45dc59d26aa20eea34154dc8972d9de0d4311f2caf",
    "algo": "sha512WithRSAEncryption",
    .
    .
   .
}
```

when I run the following code to generate a password:

```
const criton = require('criton');
  const algo = 'sha512WithRSAEncryption'; // default
  const hashPassword = criton('testserver', algo);
```
I get:
```
dfe3c8de193cace24131e50d68a8956d46f3651b0c2c350484a7dbdae9dae1e4fe1d9b2e4670c07a5aba3bf60d7a5a98861e69c6eb17e7560d2f23ac7700bb0e
```
for a hash. I don't understand why they would be different. I am presented with the authentication box, however my username and password are not accepted.

I am deploying this in a kubernetes pod. with the config options as command line args. There is not an option to specify the algorithm for encryption. 
```
containers:
        - name: testserver-cloudcmd-container
          image: coderaiser/cloudcmd
          args:
            - '--no-open'
            - '--auth'
            - '--root=/data'
            - '--no-console'
            - '--no-terminal'
            - '--no-export'
            - '--no-import'
            - '--no-dropbox'
            - '--packer=zip'
            - '--no-contact'
            - '--no-online'
            - '--name=File Manager'
            - '--columns=name-size-date'
            - '--prefix=/fm'
            - '--log'
            - '--no-config-auth'
            - '--no-config-dialog'
            - '--port=8000'
            - '--username=testserver'
            - '--password=dfe3c8de193cace24131e50d68a8956d46f3651b0c2c350484a7dbdae9dae1e4fe1d9b2e4670c07a5aba3bf60d7a5a98861e69c6eb17e7560d2f23ac7700bb0e'
```
Any help would be greatly appreciated.
Brad
