### ISSUE TITLE
Container fails to start: Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.

### ISSUE THREAD

**Issue by yllekz** [coderaiser/cloudcmd#357]
- **Version** (`cloudcmd -v`): docker-latest (v15.9.9)
- **Node Version** `node -v`: The one that ships with the docker container
- **OS** (`uname -a` on Linux): Linux 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
- **Browser name/version**: Firefox 94.0.2
- **Used Command Line Parameters**: none, used yml config file
- **Changed Config**: n/a?

Container does not start, it just spits this out in the logs repeatedly:

``Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.``

This is my docker-compose file - deployed via Portainer stack:

```
---
version: "2.1"
services:
  cloudcmd:
    image: coderaiser/cloudcmd:latest
    ports:
      - 7000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
    restart: unless-stopped
```
