### ISSUE TITLE
--packer "zip" don't work

### ISSUE THREAD

**Issue by lpmrfentazis** [coderaiser/cloudcmd#399]
Hi guys, I am using cloudcmd in docker-compose, with this config:
```
version: '2'
services:
  web:
    ports:
      - 8000:8000
    volumes:
      - /home/planum/lorett/data:/mnt/data/
    restart: always
    image: coderaiser/cloudcmd
    command: --root /mnt/data --packer "zip" --name "lorettStation" --show-file-name --no-terminal --no-contact --no-console --one-file-panel
```

But for some reason the packer is still tar.gz
If I change the parameter manually from the interface - everything works
What am I doing wrong?

- **Version** (`cloudcmd -v`): last docker image
- **Node Version** `node -v`: last docker image
- **OS** (`uname -a` on Linux): ubuntu 22.04
- **Used Command Line Parameters**: --root /mnt/data --packer "zip" --name "lorettStation" --show-file-name --no-terminal --no-contact --no-console --one-file-panel

**Comment by coderaiser** [comment]
Try to pass packer without quotes: `—packer zip`

**Comment by rgkirch** [comment]
I tried `--packer zip` and I was not able to get it to work. I'm right clicking on a folder and then clicking "download" and I get a `.tar.gz` file instead of a `.zip` file. Does the `--packer` option control that or is it just for the "pack" option?

**Comment by coderaiser** [comment]
please provide more details: what version are you using?

**Comment by rgkirch** [comment]
Sorry. I'm using v17.3.3
I'm using docker compose and I'm passing the command args like this
```
  cloudcmd:
    image: coderaiser/cloudcmd
    volumes:
    - /mnt/user:/mnt/user:ro
    command:
    - --packer
    - zip
```
and I also tried like this
```
